[project]
name = "backend"
version = "0.1.0"
description = "Appmedica challenge backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.120.0",
    "psycopg2-binary>=2.9.11",
    "ruff>=0.14.2",
    "sqlmodel>=0.0.27",
]
